RGA/Models/ViewModels/ManageUsersViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using Microsoft.AspNet.Identity.EntityFramework;

namespace RGA.Models
{
    public class ManageUsersViewModel : RegisterViewModel
    {
        private ApplicationDbContext dbContext = ApplicationDbContext.Create();


        public ManageUsersViewModel()
        {
            var users = dbContext.Users;

            
            var selectListItem = new List<User>();

// ReSharper disable once LoopCanBeConvertedToQuery
            foreach (var user in users)
            {
                if(user.Role.Name=="Kierowca")
                    selectListItem.Add(user);
            }

            DriversSelectList = new MultiSelectList(selectListItem);
        }

        public IEnumerable<User> users
        {
            get { return dbContext.Users; }
        }

        public IEnumerable<IdentityRole> roles
        {
            get { return dbContext.Roles.OrderBy(x => x.Name); }
        }


        // [Required]
        //[DataType(DataType.)]
        [Display(Name = "Rola")]
        public string Role { get; set; }

        [Display(Name = "Przydzieleni kierowcy")]
        public ICollection<User> Drivers { get; set; }


        public SelectList RolesSelectList =
            new SelectList(
                new List<SelectListItem>()
                {
                    new SelectListItem() {Value = "Kierowca", Text = "Kierowca"},
                    new SelectListItem() {Value = "Pracownik", Text = "Pracownik"},
                    new SelectListItem() {Value = "Admin", Text = "Admin"}
                }, "Value", "Text");


        public MultiSelectList DriversSelectList { get; set; }
    }
}

RGA/Controllers/ManageUsersController.cs
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.AspNet.Identity.Owin;
using RGA.Models;

namespace RGA.Controllers
{
    public class ManageUsersController : Controller
    {
        private readonly ApplicationDbContext context = ApplicationDbContext.Create();
        private readonly CreateUserViewModel model = new CreateUserViewModel();


        // GET: ManageUsers


        private ApplicationUserManager _userManager;

        public ApplicationUserManager UserManager
        {
            get { return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>(); }
            private set { _userManager = value; }
        }

        [Authorize(Roles = "Admin")]
        public ActionResult Index()
        {
            return View("Index", model);
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Register(CreateUserViewModel model)
        {
            if (ModelState.IsValid)
            {
                var user = new User {UserName = model.Username, Email = model.Email, PhoneNumber = model.Phone};
                IdentityResult result = await UserManager.CreateAsync(user, model.Password);


                if (result.Succeeded)
                {
                    var roleStore = new RoleStore<IdentityRole>(context);
                    var roleManager = new RoleManager<IdentityRole>(roleStore);

                    var userStore = new UserStore<User>(context);
                    var userManager = new UserManager<User>(userStore);
                    userManager.AddToRole(user.Id, model.Role);
                    // await SignInManager.SignInAsync(user, isPersistent: false, rememberBrowser: false);

                    // For more information on how to enable account confirmation and password reset please visit http://go.microsoft.com/fwlink/?LinkID=320771
                    // Send an email with this link
                    // string code = await UserManager.GenerateEmailConfirmationTokenAsync(user.Id);
                    // var callbackUrl = Url.Action("ConfirmEmail", "Account", new { userId = user.Id, code = code }, protocol: Request.Url.Scheme);
                    // await UserManager.SendEmailAsync(user.Id, "Confirm your account", "Please confirm your account by clicking <a href=\"" + callbackUrl + "\">here</a>");

                    //return RedirectToAction("Index", "Home");
                    ///   model = new CreateUserViewModel();
                    return View("Index", model);
                }
                AddErrors(result);
            }

            // If we got this far, something failed, redisplay form
            return View("Index", model);
        }

        private void AddErrors(IdentityResult result)
        {
            foreach (string error in result.Errors)
            {
                ModelState.AddModelError("", error);
            }
        }


        [Authorize(Roles = "Admin")]
        // GET: ManageUsers/Delete/5
        public ActionResult Delete(string id)
        {
            //var model = new CreateUserViewModel();
            // var dbContext = ApplicationDbContext.Create();
            //   dbContext.Users.Remove(dbContext.Users.Find(id));
            User user = UserManager.FindById(id);
            IdentityResult result = UserManager.Delete(user);

            // model = new CreateUserViewModel();
            if (result.Succeeded)
            {
                return View("Index", model);
            }
            AddErrors(result);

            return View("Index", model);
        }
    }
}

RGA/Views/ManageUsers/Index.cshtml
@using RGA.Models
@model RGA.Models.CreateUserViewModel

@{
    ViewBag.Title = "Edytuj użytkowników";
    //Layout = "_Layout";
    //var model = new CreateUserViewModel();
}

<h2>Edytuj użytkowników</h2>

<table border="1">
    <thead>
        <tr>
            <td>Id</td>
            <td>Nazwa</td>
            <td>E-mail</td>
            <td>Numer telefonu</td>
            <td>Rola</td>
            <td> </td>
            <td> </td>
        </tr>
    </thead>
    <tbody>
        @foreach (User item in Model.users)
        {
            <tr>
                <td>
                    @Html.Encode(item.Id)
                </td>

                <td>
                    @Html.Encode(item.UserName)
                </td>

                <td>
                    @Html.Encode(item.Email)
                </td>

                <td>
                    @Html.Encode(item.PhoneNumber)
                </td>

                <td>
                    @Html.Encode(item.Role.Name)
                </td>
                <td>
                    @Html.ActionLink("Edytuj", "Edit", new {item.Id})
                </td>
                <td>
                    @Html.ActionLink("Usuń", "Delete", new {item.Id})
                </td>
            </tr>
        }
    </tbody>
</table>

<br/>

<h2>Dodaj użytkownika</h2>


@using (Html.BeginForm("Register", "ManageUsers", FormMethod.Post, new {@class = "form-horizontal", role = "form"}))
{
    @Html.AntiForgeryToken()
    <h4>Utwórz nowe konto.</h4>
    <hr />
    @Html.ValidationSummary("", new {@class = "text-danger"})
    <div class="form-group">
        @Html.LabelFor(m => m.Username, new {@class = "col-md-2 control-label"})
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Username, new {@class = "form-control"})
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Email, new {@class = "col-md-2 control-label"})
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Email, new {@class = "form-control"})
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.Phone, new {@class = "col-md-2 control-label"})
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Phone, new {@class = "form-control"})
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.Role, new {@class = "col-md-2 control-label"})
        <div class="col-md-10">
            @Html.ListBoxFor(m => m.Role,
                new SelectList(new List<SelectListItem> {new SelectListItem {Value = "Kierowca", Text = "Kierowca", Selected = true}, new SelectListItem {Value = "Pracownik", Text = "Pracownik"}, new SelectListItem {Value = "Admin", Text = "Admin"}}, "Value", "Text"),
                new {@class = "form-control"})
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.Password, new {@class = "col-md-2 control-label"})
        <div class="col-md-10">
            @Html.PasswordFor(m => m.Password, new {@class = "form-control"})
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.ConfirmPassword, new {@class = "col-md-2 control-label"})
        <div class="col-md-10">
            @Html.PasswordFor(m => m.ConfirmPassword, new {@class = "form-control"})
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-default" value="Register" />
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}