RGA/Models/CalendarViewModel.cs
using System.Web;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;

namespace RGA.Models.ViewModels
{
    public class CalendarViewModel
    {
        private ApplicationDbContext dbContext = ApplicationDbContext.Create();

        public CalendarViewModel()
        {
            var store = new UserStore<User>(new ApplicationDbContext());
            var userManager = new UserManager<User>(store);
            User = userManager.FindByName(HttpContext.Current.User.Identity.Name);
        }


        public string WorkDatesForUser { get; set; }

        public User User { get; set; }
    }
}

RGA/Models/ViewModels/CouriersViewModel.cs
using System.Collections.Generic;
using System.Web;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;

namespace RGA.Models.ViewModels
{
    public class CouriersViewModel
    {
        private readonly User user;
        private ApplicationDbContext dbContext = ApplicationDbContext.Create();

        public CouriersViewModel()
        {
            var store = new UserStore<User>(new ApplicationDbContext());
            var userManager = new UserManager<User>(store);
            user = userManager.FindByNameAsync(HttpContext.Current.User.Identity.Name).Result;
        }

        public IEnumerable<User> drivers
        {
            get { return user.Drivers; }
        }
    }


    public class CourierCalendarViewModel
    {
        private readonly User user;
        private ApplicationDbContext dbContext = ApplicationDbContext.Create();

        public CourierCalendarViewModel()
        {
            var store = new UserStore<User>(new ApplicationDbContext());
            var userManager = new UserManager<User>(store);
            user = userManager.FindByNameAsync(HttpContext.Current.User.Identity.Name).Result;
        }


        public string WorkDatesForDriver { get; set; }

        public User SelectedDriver { get; set; }

        public IEnumerable<User> drivers
        {
            get { return user.Drivers; }
        }
    }
}

RGA/Controllers/CalendarController.cs
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using RGA.Models;
using RGA.Models.ViewModels;

namespace RGA.Controllers
{
    public class CalendarController : Controller
    {
        // GET: Calendar
        [Authorize(Roles = "Kierowca")]
        public ActionResult Index()
        {
            var model2 = new CalendarViewModel();


            ApplicationDbContext db = ApplicationDbContext.Create();

            var store = new UserStore<User>(db);
            var userManager = new UserManager<User>(store);
            User user = userManager.FindByName(System.Web.HttpContext.Current.User.Identity.Name);

            model2.User = user;


            List<Route> allRoutes = db.Routes.ToList();

            List<Route> thisDriverRoutes = allRoutes.FindAll(r => r.Driver.Id == model2.User.Id);

            model2.WorkDatesForUser = "";

            var sb = new StringBuilder();

            foreach (Route driverRoute in thisDriverRoutes)
            {
                sb.AppendFormat(@" ""{0}"",", driverRoute.StartDateTime.ToShortDateString());
            }
            sb.Remove(sb.Length - 1, 1);

            model2.WorkDatesForUser = sb.ToString();

            return View(model2);
        }

        //<div id="datepicker"></div>
    }
}

RGA/Controllers/CouriersController.cs
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using RGA.Models;
using RGA.Models.ViewModels;

namespace RGA.Controllers
{
    public class CouriersController : Controller
    {
        private readonly CouriersViewModel model = new CouriersViewModel();

        // GET: Couriers
        [Authorize(Roles = "Pracownik")]
        public ActionResult Index()
        {
            return View(model);
        }

        //new{User.Identity.GetUserId<string>()}
        [Authorize(Roles = "Pracownik")]
        public ActionResult Calendar(string id)
        {
            var store = new UserStore<User>(new ApplicationDbContext());
            var userManager = new UserManager<User>(store);

            var model2 = new CourierCalendarViewModel();


            model2.SelectedDriver = userManager.FindById(id);


            ApplicationDbContext dbContext = ApplicationDbContext.Create();

            List<Route> allRoutes = dbContext.Routes.ToList();

            List<Route> thisDriverRoutes = allRoutes.FindAll(r => r.Driver.Id == model2.SelectedDriver.Id);

            model2.WorkDatesForDriver = "";

            var sb = new StringBuilder();

            foreach (Route driverRoute in thisDriverRoutes)
            {
                sb.AppendFormat(@" ""{0}"",", driverRoute.StartDateTime.ToShortDateString());
            }
            if (sb.Length > 0)
                sb.Remove(sb.Length - 1, 1);

            model2.WorkDatesForDriver = sb.ToString();

            return View(model2);
        }
    }
}

RGA/Views/Couriers/Calendar.cshtml
@model RGA.Models.ViewModels.CourierCalendarViewModel

@{
    ViewBag.Title = "Kalendarz kierowcy " + Model.SelectedDriver.UserName;
}

<h2>Kalendarz dla kierowcy @Model.SelectedDriver.UserName</h2>

<style>
    .bolddate a {
        color: #000000 !important;
        font-weight: bold !important;
    }
</style>



<div id="datepicker"></div>
<br />
<p>
    @Html.ActionLink("Zobacz trasę dzienną", "ShowDailyRoute", "Routes", new {Model.SelectedDriver.Id, date = DateTime.Today.ToShortDateString()}, new {id = "showDailyRoute", @class = "btn btn-default"})
</p>

<br />
<p>
    @Html.ActionLink("Generuj trasę dzienną", "GenerateRoute", "Routes", new {Model.SelectedDriver.Id, date = DateTime.Today.ToShortDateString()}, new {id = "generateRoute", @class = "btn btn-primary btn-lg"})
</p>





@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script>
        var workDatesArrayNnNu32gf23gih9f3 = new Array(@Html.Raw(Model.WorkDatesForDriver));

        $(document).ready(function() {

            $('#datepicker').datepicker({
                regional: "pl",
                dateFormat: 'yy-mm-dd',
                //minDate: 0,
                showWeek: true,
                firstDay: 1,
                showButtonPanel: true,
                beforeShowDay: bolddates,
                onSelect: setVisualsAccordingToSelectedDate
            });

            $("#datepicker").css({ 'font-size': 24 });

            setVisualsAccordingToSelectedDate("@DateTime.Today.ToShortDateString()");
        });


        function setVisualsAccordingToSelectedDate(date) {
            $('#generateRoute').prop("href", $('#generateRoute').prop("href").substr(0, $('#generateRoute').prop("href").indexOf("?date=")) + "?date=" + date);
            $('#showDailyRoute').prop("href", $('#showDailyRoute').prop("href").substr(0, $('#showDailyRoute').prop("href").indexOf("?date=")) + "?date=" + date);

            var dt = new Date(date);
            dt.setHours(0, 0, 0, 0);

            var nowdt = new Date(Date.now());
            nowdt.setHours(0, 0, 0, 0);

            var indexOfDateInWorkDatesArray = $.inArray(date, workDatesArrayNnNu32gf23gih9f3);

            if (indexOfDateInWorkDatesArray == -1) {
                $('#showDailyRoute').hide();

                if (dt >= nowdt)
                    $('#generateRoute').show();

            } else {
                $('#showDailyRoute').show();
                $('#generateRoute').hide();
            }
        }


        function bolddates(date) {


            var dt = new Date(date);
            dt.setHours(0, 0, 0, 0);

            var xday = date.getDate();
            var xmonth = date.getMonth() + 1; //jan is 0
            var xyear = date.getFullYear();


            var xfulldate = xyear + "-";

            if (xmonth < 10)
                xfulldate += "0" + xmonth + "-";
            else
                xfulldate += xmonth + "-";

            if (xday < 10)
                xfulldate += "0" + xday;
            else
                xfulldate += xday;

            var xboldthese = workDatesArrayNnNu32gf23gih9f3;
            var xcssflg = "";
            for (var i = 0; i < xboldthese.length; i++) {
                if (xfulldate == xboldthese[i]) {
                    xcssflg = "bolddate";
                } else {
                    //maybe some other css class
                }
            }
            return [true, xcssflg];
        }
    </script>
}

RGA/Views/Couriers/Index.cshtml
@using RGA.Models
@model RGA.Models.ViewModels.CouriersViewModel

@{
    ViewBag.Title = "Zarządzaj kierowcami";
}

<h2>Kierowcy z którymi współpracujesz</h2>


<table class="table">
    <tr>
        <th>Nazwa</th>
        <th>E-mail</th>
        <th>Numer telefonu</th>
        <th> </th>
    </tr>

    @foreach (User item in Model.drivers)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.UserName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.PhoneNumber)
            </td>

            <td>
                @Html.ActionLink("Kalendarz", "Calendar", new {item.Id})
            </td>
        </tr>
    }

</table>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}